### ISSUE TITLE
Include list of available rules in the docs

### ISSUE THREAD

**Issue by mcbanderson** [cloudmitigator/reflex-docs#16]
Ideally this will be automatically generated via the manifest

**Comment by rot26** [comment]
Alternative: we could supply a link to the github search.
i.e.:
https://github.com/cloudmitigator?q=reflex-aws-

Or were you trying to cover descriptions too?

**Comment by mcbanderson** [comment]
That's an easy short term solution, so I think that'll work for now.

Long term I'd still like to generate a more user friendly list to be included in the official documentation.

**Comment by mcbanderson** [comment]
This has been resolved via Chris' suggested method of linking to GitHub with an appropriate filter.
