### ISSUE TITLE
Switch to using markdown

### ISSUE THREAD

**Issue by mcbanderson** [cloudmitigator/reflex-docs#18]
If it's feasible to switch to `.md` from `.rst` we probably should.

https://www.sphinx-doc.org/en/master/usage/markdown.html

**Comment by mcbanderson** [comment]
Counterpoint: https://buttondown.email/hillelwayne/archive/please-dont-write-your-documentation-in-markdown/

**Comment by rjulian** [comment]
I'm pretty much a heavy :man_shrugging: on this discussion, rst seems fairly straightforward.

**Comment by MikeSchapp** [comment]
I'd say stick with rst, not too hard to work with. Think we can close this if you feel satisfied @mcbanderson
