### ISSUE TITLE
Add more information on how to install Reflex

### ISSUE THREAD

**Issue by mcbanderson** [cloudmitigator/reflex-docs#7]
Ideally we should have sections on how to install Reflex on different operating systems (MacOS, Windows, Linux). Adding support for this could require engineering work on the tool in order to more easily support various installation methods.

Also should include information about how to install dependencies which Reflex requires in order to run (Terraform, python, etc.)

**Comment by rjulian** [comment]
@mcbanderson At this point, I don't feel like there's much more to explain since the install commands should be platform independent. We should rely on the terraform and python websites to outline how to install their software.

**Comment by mcbanderson** [comment]
I agree we should rely on (and link to) the Python and Terraform installation pages for providing that info.

I do think we should try to provide info on how to install from source, if possible, if for whatever reason people can't or don't want to use pip. But if you think that's not particularly valuable I'm ok with not adding it.
